runtime: python27
api_version: 1
threadsafe: true

# Comment the following lines to use jinja2.10 installed from pip
libraries:
- name: jinja2
  version: "2.6"

handlers:
- url: /.*
  script: main.app
